package: bs5_iconpicker 
version: '2.0.0' 
author: 'Alexander Walther, Thorben' 
supportpage: https://github.com/alexplusde/bs5_iconpicker 


requires:
    php:
        version: '>7.3,<9'
    redaxo: ^5.17

page:
    title: translate:bs5_iconpicker_title
    hidden: true
