package: bs5_iconpicker 
version: '1.0.0' 
author: 'Alexander Walther' 
supportpage: https://github.com/alexplusde/bs5_iconpicker 


requires:                       
    php:
        version: '>7.3,<9'
    redaxo: ^5.13              

page:
    title: translate:bs5_iconpicker_title    
    prio: 100                       
